services:
  reactecommercestore.api:
    env_file: "/ReactECommerceStore.Api/.env.dev"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ConnectionStrings__DefaultConnection=Server=${PGHOST};Port=${PGPORT};User Id=${PGUSER};Password=${PGPASSWORD};Database=${PGDATABASE}
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      postgres:
        condition: service_healthy

  # reactecommercestore.client:
  #   image: reactestore_client:dev
  #   container_name: reactestore_client
  #   build:
  #     context: ./reactecommercestore.client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./reactecommercestore.client:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - reactecommercestore.api

  postgres:
    image: postgres:alpine
    container_name: reactestore_postgres
    restart: "unless-stopped"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ecommerce_db_pg_data:/var/lib/postgresql/data
    ports: 
     - "${PGPORT}:${PGPORT}"
    
volumes:
 ecommerce_db_pg_data: