services:
  api:
    image: ghcr.io/ryancathcart/react-ecommerce-store:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8080:80"
      - "8081:443"
    env_file: ".env"
    environment:
      ConnectionString: Server=${PGHOST};Port=${PGPORT};User Id=${PGUSER};Password=${PGPASSWORD};Database=${PGDATABASE}
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: "unless-stopped"
    container_name: postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - react_estore_pg_db_data:/var/lib/postgresql/data
    ports: 
     - "5432:5432"
    
volumes:
  react_estore_pg_db_data: